name: Deploy to AWS on Push

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: "compdemocracy/polis"
          path: polis

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create deployment package
        working-directory: polis
        run: |
          zip -r deployment.zip appspec.yml scripts/* docker-compose.yml
  
      - name: Upload deployment package to S3
        working-directory: polis
        run: |
          aws s3 cp deployment.zip s3://preprod-polis-deployment-packages-939472767309-us-east-1/deployments/deployment.zip
  
      - name: Create CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name PreprodPolisApplication \
            --deployment-group-name PreprodPolisDeploymentGroup \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --revision revisionType=S3,s3Location="{bucket=preprod-polis-deployment-packages-939472767309-us-east-1,key=deployments/deployment.zip,bundleType=zip}" \
            --region us-east-1